environment:
  matrix:
    - node_js: 6
    - node_js: 8
    - node_js: 9

build: off

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - yarn

test_script:
  - yarn test

cache:
 - "%LOCALAPPDATA%\\Yarn"

init:
  - git config --global core.autocrlf input
  - ps: Install-Product node $env:node_js
